### ISSUE TITLE
[FR] Pure boosts, `canonical_angles`, and `canonical_wigner_rotations`

### ISSUE THREAD

**Issue by mmikhasenko** [KaiHabermann/decayangle#44]
Implement two new functions,

`canonical_angles`, and `canonical_wigner_rotations`

## Canonical angular variables

The function `helicity_angles` works nicely and gives the values of the angles according to the topology.
In order to arrive to a new frame, we do `B^{-1} R^{-1}`. That is how the helicity frame is introduced.

Instead of _helicity_ quantization, one can deal with _canonical_ quantization. In this approach, the transition between frames is done as

`B_{pure}^{-1} = R B^{-1} R^{-1}`

i.e. one arrived to the helicity frame an extra rotation that is matching the inverse rotation before boost is applied.

## Canonical Wigner rotations 

The Wigner rotations are defined exactly the same way as before.
Following topology1 and topology to the rest frame of the of every particle, one get two sequences of transformations that differ by a rotation.

## Reference

Here is a paper
https://inspirehep.net/literature/2613888
which discusses construction of amplitude (presumably equivalent) using entirely LS basis, and pure boosts.

**Comment by KaiHabermann** [comment]
So do I understand correctly, that in this we would just append this extra rotation while traversing the decay tree and that is it? 
Because if so, then a simpel flag should work this nicely in the code.

**Comment by mmikhasenko** [comment]
That is right, adding an extra rotation, also angels are computed accordingly, they won't be the same except the very first pair

**Comment by KaiHabermann** [comment]
One more question: The canonical approach will introduce another rotation after the boost. We calculate helicity angles as the angle we need to rotate in order to align the new particles momentum with the z-axis. Now when we have this extra rotation, the helicity angles would be different right?
Is helicity angles then even the correct term anymore? Since the second rotation moves us away from the mother particles initial projection axis. We would now (I beliefe) use the quantization axis of the very first particle in the decay chain, if I am not mistaken.
